apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
  - nodePort: 30580
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  