services:
  python:
    image: krajewskim/python-api:new
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      LOG_LEVEL: INFO
    ports:
      - 5002:5002
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 3
volumes:
  redis_data: