apiVersion: v1
kind: Pod
metadata:
  name: python-api
  labels:
    name: python-api
spec:
  enableServiceLinks: false
  containers:
  - name: python-api
    image: krajewskim/python-api:new
    ports:
      - containerPort: 5002
        name: api
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: api
    readinessProbe:
      tcpSocket:
        port: api